version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_jsyme
      - POSTGRES_PASSWORD=postgres_jsyme_pass123!
      - POSTGRES_DB=jsyme_dev
    ports:
      - 5432:5432
  django:
    build:
      context: ./jsyme
    volumes:
      - ./jsyme:/usr/src/app
      - ./jsyme/static:/usr/src/app/static
      - ./jsyme/media:/usr/src/app/media
    env_file:
      - jsyme/.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data_dev: {}
